package modelo;
// Generated 26 nov 2025, 12:04:36 by Hibernate Tools 6.5.1.Final

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Pelicula generated by hbm2java
 */
public class Pelicula implements java.io.Serializable {

	private Integer codigo;
	private String titulo;
	private String director;
	private int anioEstreno;
	private int duracion;
	private BigDecimal recaudacion;
	private BigDecimal puntuacion;
	private Set personajes = new HashSet(0);

	public Pelicula() {
	}

	public Pelicula(String titulo, String director, int anioEstreno, int duracion, BigDecimal recaudacion,
			BigDecimal puntuacion) {
		this.titulo = titulo;
		this.director = director;
		this.anioEstreno = anioEstreno;
		this.duracion = duracion;
		this.recaudacion = recaudacion;
		this.puntuacion = puntuacion;
	}

	public Pelicula(String titulo, String director, int anioEstreno, int duracion, BigDecimal recaudacion,
			BigDecimal puntuacion, Set personajes) {
		this.titulo = titulo;
		this.director = director;
		this.anioEstreno = anioEstreno;
		this.duracion = duracion;
		this.recaudacion = recaudacion;
		this.puntuacion = puntuacion;
		this.personajes = personajes;
	}

	public Integer getCodigo() {
		return this.codigo;
	}

	public void setCodigo(Integer codigo) {
		this.codigo = codigo;
	}

	public String getTitulo() {
		return this.titulo;
	}

	public void setTitulo(String titulo) {
		this.titulo = titulo;
	}

	public String getDirector() {
		return this.director;
	}

	public void setDirector(String director) {
		this.director = director;
	}

	public int getAnioEstreno() {
		return this.anioEstreno;
	}

	public void setAnioEstreno(int anioEstreno) {
		this.anioEstreno = anioEstreno;
	}

	public int getDuracion() {
		return this.duracion;
	}

	public void setDuracion(int duracion) {
		this.duracion = duracion;
	}

	public BigDecimal getRecaudacion() {
		return this.recaudacion;
	}

	public void setRecaudacion(BigDecimal recaudacion) {
		this.recaudacion = recaudacion;
	}

	public BigDecimal getPuntuacion() {
		return this.puntuacion;
	}

	public void setPuntuacion(BigDecimal puntuacion) {
		this.puntuacion = puntuacion;
	}

	public Set getPersonajes() {
		return this.personajes;
	}

	public void setPersonajes(Set personajes) {
		this.personajes = personajes;
	}

	@Override
	public String toString() {
		return "Pelicula [codigo=" + codigo + ", titulo=" + titulo + ", director=" + director + ", anioEstreno="
				+ anioEstreno + ", duracion=" + duracion + ", recaudacion=" + recaudacion + ", puntuacion=" + puntuacion
				+ "]";
	}

}
