package modelo;
// Generated 26 nov 2025, 12:04:36 by Hibernate Tools 6.5.1.Final

/**
 * PersonajeId generated by hbm2java
 */
public class PersonajeId implements java.io.Serializable {

	private int codigoActor;
	private int codigoPelicula;

	public PersonajeId() {
	}

	public PersonajeId(int codigoActor, int codigoPelicula) {
		this.codigoActor = codigoActor;
		this.codigoPelicula = codigoPelicula;
	}

	public int getCodigoActor() {
		return this.codigoActor;
	}

	public void setCodigoActor(int codigoActor) {
		this.codigoActor = codigoActor;
	}

	public int getCodigoPelicula() {
		return this.codigoPelicula;
	}

	public void setCodigoPelicula(int codigoPelicula) {
		this.codigoPelicula = codigoPelicula;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PersonajeId))
			return false;
		PersonajeId castOther = (PersonajeId) other;

		return (this.getCodigoActor() == castOther.getCodigoActor())
				&& (this.getCodigoPelicula() == castOther.getCodigoPelicula());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getCodigoActor();
		result = 37 * result + this.getCodigoPelicula();
		return result;
	}

}
