package modelo;
// Generated 26 nov 2025, 12:04:36 by Hibernate Tools 6.5.1.Final

/**
 * Personaje generated by hbm2java
 */
public class Personaje implements java.io.Serializable {

	private PersonajeId id;
	private Actor actor;
	private Pelicula pelicula;
	private int salario;
	private String nombre;
	private String rol;
	private String descripcion;

	public Personaje() {
	}

	public Personaje(PersonajeId id, Actor actor, Pelicula pelicula, int salario, String nombre, String rol) {
		this.id = id;
		this.actor = actor;
		this.pelicula = pelicula;
		this.salario = salario;
		this.nombre = nombre;
		this.rol = rol;
	}

	public Personaje(PersonajeId id, Actor actor, Pelicula pelicula, int salario, String nombre, String rol,
			String descripcion) {
		this.id = id;
		this.actor = actor;
		this.pelicula = pelicula;
		this.salario = salario;
		this.nombre = nombre;
		this.rol = rol;
		this.descripcion = descripcion;
	}

	public PersonajeId getId() {
		return this.id;
	}

	public void setId(PersonajeId id) {
		this.id = id;
	}

	public Actor getActor() {
		return this.actor;
	}

	public void setActor(Actor actor) {
		this.actor = actor;
	}

	public Pelicula getPelicula() {
		return this.pelicula;
	}

	public void setPelicula(Pelicula pelicula) {
		this.pelicula = pelicula;
	}

	public int getSalario() {
		return this.salario;
	}

	public void setSalario(int salario) {
		this.salario = salario;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getRol() {
		return this.rol;
	}

	public void setRol(String rol) {
		this.rol = rol;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Override
	public String toString() {
		return "Personaje [id=" + id + ", actor=" + actor.getCodigo() + ", pelicula=" + pelicula.getCodigo() + ", salario=" + salario
				+ ", nombre=" + nombre + ", rol=" + rol + ", descripcion=" + descripcion + "]";
	}

}
